### PR TITLE
feature/#18549--likvido-worker-azurestoragequeue--enable-having-several-message-processors-for-the-same-queue

### PR DESCRIPTION
**Pull request by spewu**
Likvido/Likvido.App#18549

### CODE REVIEW

**Review by leodip — APPROVED** [review]
It looks good to me!
Regarding the `EventTypeHandlerMapping` property, is it worth adding an example, in the documentation? I see you're already describing it, but I was curious to see an example of the type declaration.

**Comment by spewu** [comment]
> It looks good to me! Regarding the `EventTypeHandlerMapping` property, is it worth adding an example in the documentation? I see you're already describing it, but I was curious to see an example of the type declaration.

When you say documentation, do you mean Notion?

I did add an example in the README.md: https://github.com/Likvido/Likvido.Worker.AzureStorageQueue/pull/40/commits/6d4b01c4b5b752658e87278158b33f6fe61a1bab

I think once I have updated all of our current projects to use this version, the need for more documentation is a lot less, since you can go and look at any queue-processing robots 😁

**Comment by leodip** [comment]
No, sorry, not Notion :-)

I meant this (and missed you had already added it).



When it's not a star, what's a typical value for the CloudEvent.Type? A full namespaced class name?

**Comment by spewu** [comment]
> No, sorry, not Notion :-)
> 
> I meant this (and missed you had already added it).
> 
> 
> 
> When it's not a star, what's a typical value for the CloudEvent.Type? A full namespaced class name?

No, a typical value for an event type could be `invoice.created` (like the line above the star line shows 😁)

**Comment by leodip** [comment]
Of course. Understood :-) 
The context switching and poor sleep is messing with my brain!

**Pull request merged**
